TAG ?= latest
REGISTRY_ID ?= 014125565833
REPOSITORY_REGION ?= eu-central-1
APP ?= web
ENV ?= dev
NAME_CONTAINER ?= apache
REPO_NAME = $(REGISTRY_ID).dkr.ecr.$(REPOSITORY_REGION).amazonaws.com/$(APP)-$(ENV)-$(NAME_CONTAINER)

.PHONY: build
build:
	$(MAKE) docker-login
	docker build -t $(REPO_NAME):$(TAG) ./web/
	docker push $(REPO_NAME):$(TAG)

.PHONY: docker-login
docker-login:
	aws ecr get-login-password --region $(REPOSITORY_REGION) | docker login --username AWS --password-stdin $(REGISTRY_ID).dkr.ecr.$(REPOSITORY_REGION).amazonaws.com
